{{- if .Values.provider.vsphere.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-vsphere
  name: capv-manager-bootstrap-credentials
  namespace: capv-system
stringData:
  credentials.yaml: |-
    username: {{ .Values.provider.vsphere.credentials.username }}
    password: {{ .Values.provider.vsphere.credentials.password }}
type: Opaque
{{- end -}}