apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
  
spec:
  project: default
  source:
    path: apps
    repoURL: https://github.com/hojun121/argocd-app-of-apps.git
    targetRevision: master

  destination:
    namespace: default
    server: "https://kubernetes.default.svc"

  syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
    syncOptions:
      - CreateNamespace=true
