apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set
  namespace: argocd
  #finalizers:
    #- resources-finalizer.argocd.argoproj.io    
    
spec:
  generators:
  - list:
      elements:
      - app: apache 
      - app: jenkins
      - app: nginx
      - app: tomcat             

  template:
    metadata:
      name: '{{app}}'

    spec:
      project: default

      source:
        repoURL: https://github.com/hojun121/argocd-app-of-apps.git
        targetRevision: master
        path: charts/{{app}}

      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{app}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
