apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  labels:
    argocd.argoproj.io/refresh: hard
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  sources:
    - repoURL: https://github.com/hojun121/argocd-app-of-apps.git  # path is missing so no manifests are generated
      targetRevision: master
      ref: myRepo                                         # repo is available via symlink "myRepo"
    - repoURL: https://github.com/bitnami/charts.git
      targetRevision: HEAD
      path: bitnami/nginx                                 # path "bitnami/nginx" is used to generate manifests
      helm:
        valueFiles:
          - $myRepo/values/nginx-values.yaml                  # "values/nginx-values.yaml" is located in source with reference name $myRepo
