{{- if .Values.provider.aws.enabled -}}
{{- $encoded := b64enc (printf "[default]\naws_access_key_id = %s\naws_secret_access_key = %s\nregion = %s" .Values.provider.aws.credentials.accessKeyID .Values.provider.aws.credentials.secretAccessKeyID .Values.provider.aws.credentials.region) }}
apiVersion: v1
data:
  credentials: {{ $encoded | quote }}
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: infrastructure-aws
  name: capa-manager-bootstrap-credentials
  namespace: capa-system
type: Opaque
{{- end -}}