{{- if eq (include "harbor.autoGenCertForIngress" .) "true" }}
{{- $ca := genCA "harbor-ca" 365 }}
{{-  $notaryDomain := printf "%s.%s" .Values.expose.ingress.hosts.notary  .Values.expose.ingress.hosts.domain -}}
{{-  $coreDomain := printf "%s.%s" .Values.expose.ingress.hosts.core  .Values.expose.ingress.hosts.domain -}}

{{- $cert := genSignedCert .Values.expose.ingress.hosts.core nil (list $coreDomain $notaryDomain) 365 $ca }}
kind: Secret
apiVersion: v1
metadata:
  name: "{{ template "harbor.ingress" . }}"
  namespace: {{ .Values.namespace }}

  labels:
{{ include "harbor.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}
