{{ if .Values.modules.capi.enabled }}
{{ $isMaster := eq .Values.global.cluster "master" }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "cluster-api" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
spec:
  destination:
    name: {{ .Values.global.clusterName }}
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:   
        - name: global.timeZone
          value: "{{ .Values.global.timeZone }}"
        - name: global.network.disabled
          value: "{{ .Values.global.network.disabled }}"
        - name: global.network.registry
          value: "{{ .Values.global.privateRegistry }}"

          # capi 
        - name: capi.verbose
          value: "{{ .Values.modules.capi.verbose }}"

          # aws 
        - name: provider.aws.enabled
          value: "{{ .Values.modules.capi.provider.aws.enabled }}"
        - name: provider.aws.verbose
          value: "{{ .Values.modules.capi.provider.aws.verbose }}"
        - name: provider.aws.credentials.accessKeyID
          value: "{{ .Values.modules.capi.provider.aws.credentials.accessKeyID }}"
        - name: provider.aws.credentials.secretAccessKeyID
          value: "{{ .Values.modules.capi.provider.aws.credentials.secretAccessKeyID }}"
        
        # vsphere
        - name: provider.vsphere.enabled
          value: "{{ .Values.modules.capi.provider.vsphere.enabled }}"
        - name: provider.vsphere.verbose
          value: "{{ .Values.modules.capi.provider.vsphere.verbose }}"
        - name: provider.vsphere.credentials.username
          value: "{{ .Values.modules.capi.provider.vsphere.credentials.username }}"
        - name: provider.vsphere.credentials.password
          value: "{{ .Values.modules.capi.provider.vsphere.credentials.password }}"

    path: manifest/cluster-api
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
{{ end }}