{{ $isMaster := eq .Values.global.cluster "master" }}
{{ if .Values.modules.sonarqube.enabled }}
{{ $prefix := printf "%s-%s" .Values.global.clusterNamespace .Values.global.clusterName }}
{{ $module := "sonarqube" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    cluster: {{ ternary "master" $prefix $isMaster }}
  name: {{ ternary $module (printf "%s-%s" $prefix $module) $isMaster }}
  namespace: argocd
spec:
  destination:
    name: {{ .Values.global.clusterName }}
    namespace: sonarqube
  project: {{ .Values.spec.project }}
  source:
    helm:
      parameters:
        - name: global.registry.is_offline
          value: "{{ .Values.global.network.disabled }}"
        - name: global.registry.private_registry
          value: {{ .Values.global.privateRegistry }}
        - name: global.logLevel
          value: {{ .Values.modules.sonarqube.logLevel }}
        - name: ingress.hosts.domain
          value: {{ .Values.global.domain }}
    path: manifest/sonarqube
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
{{ end }}
