tls:
  domain: ""
  acme:
    enabled: false
    email: "temp@tmax.co.kr"
    dns:
      type: route53
      accessKeyID: accessKeyID
      accessKeySecret: accessKeySecret
      hostedZoneID: hostZoneID
    # staging or production
    environment: staging
  selfsigned:
    enabled: false
  # Create an IngressRoute for the dashboard
dashboard:
  enabled: true
  # optional: dashboard login id
  id: ""
  # optional: dashboard login password
  password: ""

traefik:
  enabled: true
  fullnameOverride: gateway
  additionalArguments:
    - "--entrypoints.websecure.http.middlewares=api-gateway-system-cors-header@kubernetescrd"
    - "--providers.file"
    - "--providers.file.directory=/gateway-config"
    - "--providers.file.watch=true"
    #- "--serverstransport.insecureskipverify" # Disable SSL certificate verification. (Default: false)
  image:
    name: traefik
    tag: "v2.8.7"
  deployment:
    podLabels:
      app: traefik
    imagePullSecrets: []
    #  imagePullSecrets:
    #    - name: regcred
  volumes:
    - mountPath: /gateway-config
      name: gateway-config
      type: configMap
    - mountPath: /var/run/secrets/tmaxcloud
      name: selfsigned-ca
      type: secret
  service:
    # LoadBalancer , NodePort
    type: LoadBalancer
    # 우태건 실장님 요청으로 aws nlb annotation 추가
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"
  env:
    - name: TZ
      value: Asia/Seoul
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: Exists
  logs:
    # Traefik logs concern everything that happens to Traefik itself (startup, configuration, events, shutdown, and so on).
    general:
      # By default, the logs use a text format (common), but you can
      # also ask for the json format in the format option
      format: common
      # By default, the level is set to ERROR. Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
      level: ERROR
