spec:
  destination:
    type: server
    clusterInfo: https://kubernetes.default.svc
  project: default

global:
  privateRegistry: test-registry.com
  adminUser: test@test.co.kr
  cluster: master
  clusterName: in-cluster
  clusterNamespace: default
  domain: testdomain.com

modules:
  ## Loki
  loki:
    enabled: true
    logLevel: info
    # 사용 가능한 값 : error, warn, info, debug
    loki: 
      version: 2.7.1
      volumeSize: 50Gi
      storageClass: default
    promtail:
      version: 2.7.1
  
  ### prometheus
  prometheus:
    enabled: true
    versions:
      prometheus: v2.41.0
      cmReload: v0.0.1
      cmReloader: v0.62.0
      operator: v0.62.0
      alertManager: v0.25.0
      kubeRbacProxy: v0.14.0
      kubeStateMetrics: v2.7.0
      nodeExporter: v1.5.0
      adapter: v0.10.0
    pvcSize: 10Gi

  ### grafana-operator
  grafanaOperator:
    enabled: true
    subdomain: grafana
    pvcSize: 10Gi
    operator: 
      version: v0.0.10
      imageRepo: docker.io/tmaxcloudck/grafana-operator
    grafana:
      version: "9.3.2"
      imageRepo: docker.io/grafana/grafana

  ### grafana
  grafana:
    enabled: false
    subdomain: grafana
    pvcSize: 10Gi
    version: "9.3.2"
    imageRepo: docker.io/grafana/grafana
